/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class AttributeIndex {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AttributeIndex(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttributeIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_AttributeIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long insert(String name) {
    return desrJNI.AttributeIndex_insert(swigCPtr, this, name);
  }

  public void setNames(SWIGTYPE_p_std__vectorT_char_const_p_t value) {
    desrJNI.AttributeIndex_names_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_const_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_char_const_p_t getNames() {
    long cPtr = desrJNI.AttributeIndex_names_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_char_const_p_t(cPtr, false);
  }

  public AttributeIndex() {
    this(desrJNI.new_AttributeIndex(), true);
  }

}
