/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Context extends RefCountable {
  private long swigCPtr;

  protected Context(long cPtr, boolean cMemoryOwn) {
    super(desrJNI.SWIGContextUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_Context(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean equals(Object obj) {
    if (obj instanceof Context)
      return ((Context)obj).swigCPtr == this.swigCPtr;
    return false;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public Context(String xmlTag, Context parent) {
    this(desrJNI.new_Context__SWIG_0(xmlTag, Context.getCPtr(parent), parent), true);
  }

  public Context(String xmlTag) {
    this(desrJNI.new_Context__SWIG_1(xmlTag), true);
  }

  public void setTag(Tag value) {
    desrJNI.Context_tag_set(swigCPtr, this, Tag.getCPtr(value), value);
  }

  public Tag getTag() {
    long cPtr = desrJNI.Context_tag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tag(cPtr, false);
  }

  public void setParent(Context value) {
    desrJNI.Context_parent_set(swigCPtr, this, Context.getCPtr(value), value);
  }

  public Context getParent() {
    long cPtr = desrJNI.Context_parent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Context(cPtr, false);
  }

}
