/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class EnumeratorSentence extends Disposable {
  private long swigCPtr;

  protected EnumeratorSentence(long cPtr, boolean cMemoryOwn) {
    super(desrJNI.SWIGEnumeratorSentenceUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnumeratorSentence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_EnumeratorSentence(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean MoveNext() {
    return desrJNI.EnumeratorSentence_MoveNext(swigCPtr, this);
  }

  public Sentence Current() {
    long cPtr = desrJNI.EnumeratorSentence_Current(swigCPtr, this);
    return (cPtr == 0) ? null : new Sentence(cPtr, false);
  }

  public void Reset() {
    desrJNI.EnumeratorSentence_Reset(swigCPtr, this);
  }

  public Sentence next() {
    long cPtr = desrJNI.EnumeratorSentence_next(swigCPtr, this);
    return (cPtr == 0) ? null : new Sentence(cPtr, true);
  }

  public boolean hasNext() {
    return desrJNI.EnumeratorSentence_hasNext(swigCPtr, this);
  }

}
