/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Tag {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tag(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tag obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_Tag(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tag(String xmlTag) {
    this(desrJNI.new_Tag(xmlTag), true);
  }

  public String open() {
    return desrJNI.Tag_open(swigCPtr, this);
  }

  public String close() {
    return desrJNI.Tag_close(swigCPtr, this);
  }

  public void setName(String value) {
    desrJNI.Tag_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return desrJNI.Tag_name_get(swigCPtr, this);
  }

  public String get(String key) {
    return desrJNI.Tag_get(swigCPtr, this, key);
  }

  public void set(String key, String val) {
    desrJNI.Tag_set(swigCPtr, this, key, val);
  }

}
