/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Token {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Token(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Token obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_Token(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Token(String form, Corpus corpus, Context context) {
    this(desrJNI.new_Token__SWIG_0(form, Corpus.getCPtr(corpus), corpus, Context.getCPtr(context), context), true);
  }

  public Token(String form, Corpus corpus) {
    this(desrJNI.new_Token__SWIG_1(form, Corpus.getCPtr(corpus), corpus), true);
  }

  public Token(String form, AttributeIndex index, Context context) {
    this(desrJNI.new_Token__SWIG_2(form, AttributeIndex.getCPtr(index), index, Context.getCPtr(context), context), true);
  }

  public Token(String form, AttributeIndex index) {
    this(desrJNI.new_Token__SWIG_3(form, AttributeIndex.getCPtr(index), index), true);
  }

  public Token(String form, Attributes attributes, SWIGTYPE_p_std__vectorT_TokenLink_t links, Context context) {
    this(desrJNI.new_Token__SWIG_4(form, Attributes.getCPtr(attributes), attributes, SWIGTYPE_p_std__vectorT_TokenLink_t.getCPtr(links), Context.getCPtr(context), context), true);
  }

  public Token(String form, Attributes attributes, SWIGTYPE_p_std__vectorT_TokenLink_t links) {
    this(desrJNI.new_Token__SWIG_5(form, Attributes.getCPtr(attributes), attributes, SWIGTYPE_p_std__vectorT_TokenLink_t.getCPtr(links)), true);
  }

  public int attrIndex(String name) {
    return desrJNI.Token_attrIndex(swigCPtr, this, name);
  }

  public void setForm(String value) {
    desrJNI.Token_form_set(swigCPtr, this, value);
  }

  public String getForm() {
    return desrJNI.Token_form_get(swigCPtr, this);
  }

  public void setAttributes(Attributes value) {
    desrJNI.Token_attributes_set(swigCPtr, this, Attributes.getCPtr(value), value);
  }

  public Attributes getAttributes() {
    long cPtr = desrJNI.Token_attributes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Attributes(cPtr, false);
  }

  public void setLinks(SWIGTYPE_p_std__vectorT_TokenLink_t value) {
    desrJNI.Token_links_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_TokenLink_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_TokenLink_t getLinks() {
    long cPtr = desrJNI.Token_links_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_TokenLink_t(cPtr, false);
  }

  public Context context() {
    long cPtr = desrJNI.Token_context(swigCPtr, this);
    return (cPtr == 0) ? null : new Context(cPtr, true);
  }

  public String toString() {
    return desrJNI.Token_toString(swigCPtr, this);
  }

  public void setAttribute(String key, String val) {
    desrJNI.Token_setAttribute__SWIG_0(swigCPtr, this, key, val);
  }

  public void setAttribute(String key, int val) {
    desrJNI.Token_setAttribute__SWIG_1(swigCPtr, this, key, val);
  }

  public String getAttribute(String key) {
    return desrJNI.Token_getAttribute(swigCPtr, this, key);
  }

}
