/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class TreeToken {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TreeToken(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TreeToken obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_TreeToken(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TreeToken(int id, Token token) {
    this(desrJNI.new_TreeToken(id, Token.getCPtr(token), token), true);
  }

  public void setToken(Token value) {
    desrJNI.TreeToken_token_set(swigCPtr, this, Token.getCPtr(value), value);
  }

  public Token getToken() {
    long cPtr = desrJNI.TreeToken_token_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Token(cPtr, false);
  }

  public void setId(long value) {
    desrJNI.TreeToken_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return desrJNI.TreeToken_id_get(swigCPtr, this);
  }

  public void setLeft(VectorTreeToken value) {
    desrJNI.TreeToken_left_set(swigCPtr, this, VectorTreeToken.getCPtr(value), value);
  }

  public VectorTreeToken getLeft() {
    long cPtr = desrJNI.TreeToken_left_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorTreeToken(cPtr, false);
  }

  public void setRight(VectorTreeToken value) {
    desrJNI.TreeToken_right_set(swigCPtr, this, VectorTreeToken.getCPtr(value), value);
  }

  public VectorTreeToken getRight() {
    long cPtr = desrJNI.TreeToken_right_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectorTreeToken(cPtr, false);
  }

  public String form() {
    return desrJNI.TreeToken_form(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string get(String key) {
    long cPtr = desrJNI.TreeToken_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public void set(String key, String value) {
    desrJNI.TreeToken_set(swigCPtr, this, key, value);
  }

  public int linkHead(int i) {
    return desrJNI.TreeToken_linkHead__SWIG_0(swigCPtr, this, i);
  }

  public int linkHead() {
    return desrJNI.TreeToken_linkHead__SWIG_1(swigCPtr, this);
  }

  public String linkLabel(long i) {
    return desrJNI.TreeToken_linkLabel__SWIG_0(swigCPtr, this, i);
  }

  public String linkLabel() {
    return desrJNI.TreeToken_linkLabel__SWIG_1(swigCPtr, this);
  }

  public String toString() {
    return desrJNI.TreeToken_toString(swigCPtr, this);
  }

}
