/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Attributes {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Attributes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Attributes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_Attributes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Attributes(AttributeIndex attributeIndex) {
    this(desrJNI.new_Attributes(AttributeIndex.getCPtr(attributeIndex), attributeIndex), true);
  }

  public SWIGTYPE_p_std__string get(String name) {
    long cPtr = desrJNI.Attributes_get(swigCPtr, this, name);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__string(cPtr, false);
  }

  public long index(String key) {
    return desrJNI.Attributes_index(swigCPtr, this, key);
  }

  public void insert(String key, String value) {
    desrJNI.Attributes_insert__SWIG_0(swigCPtr, this, key, value);
  }

  public void insert(String key, int value) {
    desrJNI.Attributes_insert__SWIG_1(swigCPtr, this, key, value);
  }

}
