/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class Parser extends RefCountable {
  private long swigCPtr;

  protected Parser(long cPtr, boolean cMemoryOwn) {
    super(desrJNI.SWIGParserUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Parser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        desrJNI.delete_Parser(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Parser create(String modelFile) {
    long cPtr = desrJNI.Parser_create(modelFile);
    return (cPtr == 0) ? null : new Parser(cPtr, true);
  }

  public EnumeratorSentence pipe(EnumeratorSentence tve) {
    long cPtr = desrJNI.Parser_pipe__SWIG_0(swigCPtr, this, EnumeratorSentence.getCPtr(tve), tve);
    return (cPtr == 0) ? null : new EnumeratorSentence(cPtr, true);
  }

  public EnumeratorSentence pipe(SWIGTYPE_p_Tanl__EnumeratorT_std__vectorT_Tanl__Token_p_t_p_t tve) {
    long cPtr = desrJNI.Parser_pipe__SWIG_1(swigCPtr, this, SWIGTYPE_p_Tanl__EnumeratorT_std__vectorT_Tanl__Token_p_t_p_t.getCPtr(tve));
    return (cPtr == 0) ? null : new EnumeratorSentence(cPtr, true);
  }

  public Sentence parse(Sentence sentence) {
    long cPtr = desrJNI.Parser_parse(swigCPtr, this, Sentence.getCPtr(sentence), sentence);
    return (cPtr == 0) ? null : new Sentence(cPtr, true);
  }

  public void showPerplexity() {
    desrJNI.Parser_showPerplexity(swigCPtr, this);
  }

}
